spring:
  profiles:
    active: local
  application:
    name: CareHub
  datasource:
    url: jdbc:postgresql://carehub_db:5432/carehub
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${POSTGRES_PASSWORD}
    default-schema: carehub
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  sql:
    init:
      continue-on-error: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    client-id: care-hub-scheduling-producer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 2147483647
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        linger.ms: 5
        batch.size: 32768
        spring.json.add.type.headers: false
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

logging:
  level:
    org:
      flywaydb: DEBUG
      springframework:
  swagger-ui:
    url: /api/schedules.yaml

api:
  security:
    token:
      secret: ${JWT_SECRET}
