openapi: 3.0.3
info:
  title: Nurses API
  version: 1.0.0
  description: API for managing hospital nurses
  contact:
    name: Carlos Eduardo Rincon Junior
    email: carloscaca147@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080/
    description: Local server
tags:
  - name: Nurses
    description: Operations related to hospital nurses
paths:
  /nurse:
    get:
      tags:
        - Nurses
      summary: List all nurses
      operationId: listNurses
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 0
            example: 1
        - name: perPage
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            default: 10
            example: 10
      responses:
        "200":
          description: A list of nurses
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedNurses"
  /nurse/{nurseId}:
    get:
      tags:
        - Nurses
      summary: Get a nurse by ID
      operationId: getNurse
      parameters:
        - name: nurseId
          in: path
          description: ID of the nurse to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Nurse found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Nurse"
        "400":
          description: Bad request
        "404":
          description: User not found
    put:
      tags:
        - Nurses
      summary: Update a nurse
      operationId: updateNurse
      parameters:
        - name: nurseId
          in: path
          description: ID of the nurse to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateNurse"
      responses:
        "200":
          description: Nurse updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Nurse"
        "404":
          description: Nurse not found
    delete:
      tags:
        - Nurses
      summary: Delete a nurse
      operationId: deleteNurse
      parameters:
        - name: nurseId
          in: path
          description: ID of the nurse to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: Nurse deleted
        "400":
          description: Bad request
components:
  schemas:
    UpdateNurse:
      type: object
      properties:
        name:
          type: string
          description: Name of the nurse
          maxLength: 100
          example: Carlos
        cpf:
          type: string
          description: CPF of the nurse
          maxLength: 14
          example: 121.323.232-11
        coren:
          type: string
          description: COREN of the nurse
          maxLength: 15
          example: COREN-SP-123.456-CATEGORY
    PaginatedNurses:
      type: object
      properties:
        page:
          type: integer
          example: 1
        perPage:
          type: integer
          example: 10
        total:
          type: integer
          format: int64
          example: 100
        items:
          type: array
          items:
            $ref: "#/components/schemas/Nurse"
    Nurse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Id of the nurse
          maxLength: 10
          example: 15
        name:
          type: string
          description: Name of the nurse
          maxLength: 100
          example: Carlos
        login:
          type: string
          description: Login of the nurse
          maxLength: 30
          example: rincon123
        cpf:
          type: string
          description: CPF of the nurse
          maxLength: 14
          example: 121.323.232-11
        coren:
          type: string
          description: COREN of the nurse
          maxLength: 15
          example: COREN-SP-123.456-CATEGORY
    CreateNurse:
      type: object
      properties:
        name:
          type: string
          description: Name of the nurse
          maxLength: 100
          example: Carlos
        login:
          type: string
          description: Login of the nurse
          maxLength: 30
          example: rincon123
        password:
          type: string
          description: Password of the doctor
          minLength: 5
          maxLength: 30
          example: strongPassword123
        cpf:
          type: string
          description: CPF of the nurse
          maxLength: 14
          example: 121.323.232-11
        coren:
          type: string
          description: COREN of the nurse
          maxLength: 15
          example: COREN-SP-123.456-CATEGORY
