CREATE TABLE users (
    nr_seq_user BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE roles (
    nr_seq_role BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE user_roles (
    nr_seq_user BIGINT NOT NULL,
    nr_seq_role BIGINT NOT NULL,
    PRIMARY KEY (nr_seq_user, nr_seq_role),
    FOREIGN KEY (nr_seq_user) REFERENCES users(nr_seq_user),
    FOREIGN KEY (nr_seq_role) REFERENCES roles(nr_seq_role)
);

CREATE TABLE doctors (
    nr_seq_doctor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(255),
    crm VARCHAR(20) NOT NULL,
    speciality VARCHAR(100),
    nr_seq_user BIGINT NOT NULL UNIQUE,
    FOREIGN KEY (nr_seq_user) REFERENCES users(nr_seq_user)
);

CREATE TABLE nurses (
    nr_seq_nurse BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    coren VARCHAR(20) NOT NULL,
    nr_seq_user BIGINT NOT NULL UNIQUE,
    FOREIGN KEY (nr_seq_user) REFERENCES users(nr_seq_user)
);

CREATE TABLE patients (
    nr_seq_patient BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(255),
    birth_date DATE,
    address VARCHAR(255),
    telephone VARCHAR(30),
    nr_seq_user BIGINT NOT NULL UNIQUE,
    FOREIGN KEY (nr_seq_user) REFERENCES users(nr_seq_user)
);

CREATE TABLE schedules (
    nr_seq_schedule BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nr_seq_doctor BIGINT NOT NULL,
    nr_seq_patient BIGINT NOT NULL,
    schedule_date TIMESTAMP NOT NULL,
    observation VARCHAR(500),
    status VARCHAR(20) DEFAULT 'SCHEDULE',

    FOREIGN KEY (nr_seq_doctor) REFERENCES doctors(nr_seq_doctor),
    FOREIGN KEY (nr_seq_patient) REFERENCES patients(nr_seq_patient)
);

CREATE TABLE history_records (
    nr_seq_history_record BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    schedule_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    event_type VARCHAR(100),
    event_time TIMESTAMP,
    payload TEXT,
    created_at TIMESTAMP NOT NULL
);
